name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: .
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Upgrade pip tooling
        run: |
          python -m pip install --upgrade pip wheel setuptools

      - name: Install deps
        run: |
          pip install -r requirements.txt

      - name: Show env (debug)
        run: |
          python - << 'PY'
          import sys,os
          print("CWD:", os.getcwd())
          print("PYTHONPATH:", os.environ.get("PYTHONPATH"))
          print("sys.path[0:3]:", sys.path[:3])
          PY

      - name: Run pytest
        run: pytest -q
